project_id = "iiakqkdcdqhhhrkwagtb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://app.stoecklilager.com"
additional_redirect_urls = ["http://localhost:5173"]

[auth.email]
enable_signup = false
enable_confirmations = false
